### ISSUE TITLE
Currency Exchange API Fetch

### ISSUE THREAD

**Issue by elopez08** [elopez08/currency-rep-api#5]
When the city is selected, it'll take the US currency and then converts it to the currency of the city

**Comment by RogerLi818** [comment]
the convert is ok on my end.
![image](https://user-images.githubusercontent.com/100240422/164174729-91906475-0993-4beb-a92d-458a5f8d9d66.png)
![image](https://user-images.githubusercontent.com/100240422/164174786-35967f54-f2bb-44ce-bd64-0ca282d087e4.png)
![image](https://user-images.githubusercontent.com/100240422/164174828-fef984e3-707d-4920-87cc-59fe2f9fc97d.png)
